# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: BubbleUPnP Server
version: "1.0.0"
slug: bubbleupnpserver
description: BubbleUPnP Server for Home Assistant
url: "https://github.com/zoomerlz/BubbleUPnP-Server-for-HASS"
arch:
  - aarch64
  - amd64
init: false
host_network: true
map:
  - data:rw
  - share:rw
options:
schema:
image: "bubblesoftapps/bubbleupnpserver"
